services:
  db:
    image: postgres:18.3-alpine3.23
    restart: unless-stopped
    command: >
      -c max_wal_size=4GB
      -c max_parallel_workers_per_gather=4
    #  -c log_statement=all
    env_file:
      .env
    # ports:
    #   - 5433:5432
    volumes:
      - /opt/nvme_disk/docker_data/code_server/code_projects_data/odoo19_pg18_data:/var/lib/postgresql
    labels:
      - logs.app=postgres
      - logs.env=dev
      - logs.odoo_version=19
      - logs.stack=odoo19-dev

  odoo:
    image: odoo-dev:19
    # image: odoo:19-dev
    restart: unless-stopped
    stop_grace_period: 5s
    env_file:
      .env
    # command: sleep 2000
    # ports:
    #   - 5678:5678
    #   - 8069:8069
    volumes:
      - /opt/nvme_disk/docker_data/code_server/config/workspace/odoo19/:/opt/odoo/
      - /opt/nvme_disk/docker_data/code_server/config/workspace/odoo19/customaddons/${CUSTOMADDONS_DIR}/odoo.conf:/etc/odoo.conf
      - /opt/nvme_disk/docker_data/code_server/code_projects_data/odoo19_filestore:/root/.local/share/Odoo/
    depends_on:
      - db
    labels:
      # - logging=promtail
      # - logging_jobname=containerlogs
      - logs.app=odoo
      - logs.env=dev
      - logs.odoo_version=19
      - logs.stack=odoo19-dev
      

  nginx:
    image: nginx:1.29.4-alpine3.23-slim
    restart: unless-stopped
    stop_grace_period: 5s
    env_file:
      .env
    ports:
      - 8019:80
    volumes:
      - /opt/nvme_disk/docker_data/code_server/config/workspace/odoo19/customaddons/${CUSTOMADDONS_DIR}/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - odoo
    labels:
      - logs.app=nginx
      - logs.env=dev
      - logs.odoo_version=19
      - logs.stack=odoo19-dev

  # swagger:
  #   image: swaggerapi/swagger-ui:v5.31.0
  #   env_file:
  #     .env
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - nginx
  #   #volumes:
  #   #   - ./doc:/usr/share/nginx/html/doc
  #   environment:
  #     API_URL: ${API_URL}
